source:
  name: ddos_dataset
  type: csv
  origin: kaggle
  dataset_url: https://www.kaggle.com/datasets/devendra416/ddos-datasets
  local_path: data/raw/dataset.csv
  encoding: utf-8
  delimiter: ","
  has_header: true

kafka:
  bootstrap_servers: kafka:9092
  topic: ddos-raw
  partitions: 4
  replication_factor: 1
  producer_delay_ms: 0

schema:
  label_column: Label
  label_values:
    - ddos
    - Benign
  drop_columns:
    - Unnamed: 0
    - Flow ID
  key_columns:
    - Src IP
    - Dst Port
    - Flow Duration
    - Tot Fwd Pkts
    - Tot Bwd Pkts

ingestion:
  infer_schema: false
  null_value: ""
  inf_handling: replace_with_null
  null_fill_strategy: column_mean
  dedup: true
  checkpoint_path: data/checkpoints/bronze