services:

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"          # Prefect UI
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: sqlite+aiosqlite:///./prefect.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - prefect-data:/root/.prefect

  spark-master:
    image: apache/spark:4.1.0
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"          # Spark UI
      - "7077:7077"
    volumes:
      - ..:/opt/pipeline
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 10

  spark-worker:
    image: apache/spark:4.1.0
    container_name: spark-worker
    entrypoint:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_CORES: 2
    ports:
      - "8081:8081"
    volumes:
      - ..:/opt/pipeline
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 5s
      timeout: 5s
      retries: 10

  pipeline-runner:
    image: apache/spark:4.1.0
    container_name: pipeline-runner
    working_dir: /opt/pipeline
    command: python schedule/ddos_dag.py
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - ..:/opt/pipeline
    depends_on:
      spark-worker:
        condition: service_healthy
      prefect-server:
        condition: service_healthy

volumes:
  prefect-data: